language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - SYMFONY_ENV=test

cache:
  directories:
    - $HOME/.composer

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer selfupdate
  - composer install --no-interaction --no-scripts

script:
  - ./vendor/bin/phpunit
